#!/bin/bash

args=(GRAPHITE_SERVER GRAPHITE_PORT STAT_NAME VALUE)
case "$(uname)" in
  "Darwin")
    NC_OPTS="-w0"
    ;;
  "Linux")
    NC_OPTS="-q0"
    ;;
esac

function usage {
  printargs=("${args[@]}")
  unset printargs[${#args[@]}-1]
  echo "Usage: $0 -c CONFIG" >&2
  echo "       $0 ${printargs[@]} [VALUE]" >&2
}

function validate_stat_name {
  local terminating_charset='[A-Za-z0-9]'
  local charset='[\.A-Za-z0-9_-]'
  local stat_regex="^${terminating_charset}${charset}+${terminating_charset}$"
  echo $STAT_NAME | grep -E $stat_regex >/dev/null
  if [ $? -ne 0 ]; then
    echo "STAT_NAME must be a period delimeted list of strings matching [A-Za-z0-9_-]" >&2
    exit 1
  fi
}

function validate_value {
  # match int or float only
  local number_regex='^[0-9]+([\.][0-9]+)?$'
  echo $VALUE | grep -E $number_regex >/dev/null
  if [ $? -ne 0 ]; then
    echo "VALUE must be an integer or a float" >&2
    exit 1
  fi
}

if [ "$1" = '-h' ]; then
  usage
  exit 0
fi

if [ "$1" = '-c' ]; then
  # Assign all user variables other than VALUE from config
  CONFIG=$2
  if [ ! -f $CONFIG ]; then
    echo "err: ${CONFIG} is not a valid file" >&2
    usage
    exit 1
  fi
  source $CONFIG
else
  # Assign all user variables from arguments. To add arguments, just add
  # to the list of args at the top before "VALUE" as the code below handles
  # number of args and order.
  count=0
  for i in "${args[@]}"; do
    ((count+=1))
    eval $i="$(echo "\$$count")"
  done
fi


# Validate that all necessary user variables are present.
for i in "${args[@]}"; do
  if [ "$(eval echo "\$$i")" = '' ] && [ ! "$i" = 'VALUE' ]; then
    echo "err: $i is not set" >&2
    usage
    exit 1
  fi
done

validate_stat_name

# Get VALUE from stdin if it has not been supplied already
if [ "$VALUE" = '' ]; then
  read VALUE < /dev/stdin
fi

validate_value

DATE=$(date +%s)

echo "${STAT_NAME} ${VALUE} ${DATE}" | nc $NC_OPTS $GRAPHITE_SERVER $GRAPHITE_PORT

nc_exit=$?

if [ $nc_exit -ne 0 ]; then
  echo "nc exited with status ${nc_exit}" >&2
fi
exit $nc_exit
